### ISSUE TITLE
The PDF is not rendering properly.

### ISSUE THREAD

**Issue by rathinnair** [jenasubodh/Xamarin.PDFView#2]
![nexus 5 kitkat screentshot 1](https://cloud.githubusercontent.com/assets/12009125/8024595/5683e83e-0d56-11e5-87dd-ac158f344c57.png)

While running the app I am getting the following page.

Ho I can Display my localy saved PDF through this implementation

**Comment by subodhjena** [comment]
You just have to pass the PDF path 

 _webView.LoadUrl("file:///android_asset/PDFViewer/index.html?file=" + HERE );
